/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

//import javax.swing.JOptionPane;

/**
 *
 * @author riendra
 */
public class MenuLogin extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public MenuLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        radioMember = new javax.swing.JRadioButton();
        radioAdmin = new javax.swing.JRadioButton();
        btnLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("USER ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        txtUserId.setBackground(new java.awt.Color(255, 255, 102));
        txtUserId.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtUserId.setForeground(new java.awt.Color(255, 255, 255));
        txtUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 260, 40));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("PASSWORD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        txtPassword.setBackground(new java.awt.Color(255, 255, 102));
        txtPassword.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 260, 40));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("ROLE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));

        radioMember.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        radioMember.setText("MEMBER");
        getContentPane().add(radioMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, -1, -1));

        radioAdmin.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        radioAdmin.setText("ADMIN");
        getContentPane().add(radioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, -1, -1));

        btnLogin.setBackground(new java.awt.Color(255, 255, 102));
        btnLogin.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(51, 51, 51));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_gui/LOGIN.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
//        if (txtUserId.getText().matches("(.*)'(.*)") || String.copyValueOf(txtPassword.getPassword()).matches("(.*)'(.*)")) {
//            JOptionPane.showMessageDialog(null, "Dilarang Memasukkan Simbol Petik Satu","WARNING",JOptionPane.WARNING_MESSAGE);
//        }else{
//            if (txtUserId.getText().equals("") || String.copyValueOf(txtPassword.getPassword()).equals("")) {
//                JOptionPane.showMessageDialog(null, "Username atau Password Tidak Boleh Kosong");
//            }else{
//                if (radioAdmin.isSelected()) {
//                    boolean operatinSuccess = ControllerAccount.radioAdminSelected(txtUserId.getText(), String.copyValueOf(txtPassword.getPassword()));
//                    if (operatinSuccess) {
//                        JOptionPane.showMessageDialog(null, "ANDA BERHASIL LOGIN SEBAGAI ADMIN");
//                        this.dispose();
//                        new AdminGUI().setVisible(true);
//                    }else JOptionPane.showMessageDialog(null, "GAGAL LOGIN. HARAP CEK USERNAME,PASSWORD DAN ROLE ANDA");
//                    
//                }else if (radioMember.isSelected()) {
//                    boolean operatinSuccess = ControllerAccount.radioMemberSelected(txtUserId.getText(), String.copyValueOf(txtPassword.getPassword()));
//                    if (operatinSuccess) {
//                        JOptionPane.showMessageDialog(null, "ANDA BERHASIL LOGIN SEBAGAI MEMBER");
//                        this.dispose();
//                        new MemberGUI(txtUserId.getText()).setVisible(true);
//                    }else JOptionPane.showMessageDialog(null, "GAGAL LOGIN. HARAP CEK USERNAME,PASSWORD DAN ROLE ANDA");
//                    
//                }else JOptionPane.showMessageDialog(null, "HARAP PILIH ROLE");
//            }
//        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton radioAdmin;
    private javax.swing.JRadioButton radioMember;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserId;
    // End of variables declaration//GEN-END:variables
}
